### ISSUE TITLE
Document HTTPS support

### ISSUE THREAD

**Issue by markmetcalfe** [totara/totara-docker-dev#113]
Having HTTPS support with our sites may be useful to have. It would give the advantage of letting us save common login password info, marginally increase page load speed, and would stop that warning message when installing/upgrading totara via the web UI.

To implement this we would need to add a server {} directive for the 443 port in the nginx server.conf, and would need to create a root certificate that supports all the ```totaraXX```/```totaraXX.debug``` hosts. Then the dev using docker-dev would need to manually add the root cert to their system's trusted certs.

**Comment by derschatta** [comment]
HTTPS support is already there :)

**Comment by derschatta** [comment]
It's just not documented

**Comment by derschatta** [comment]
hm doesn't seem to work anymore, need to check and fix it

**Comment by markmetcalfe** [comment]
Yeah ideally this repo would include a pem/key so you can easily add it to your host system's trusted certs - I don't see the cert file currently.

**Comment by derschatta** [comment]
started to improve this but it turns out to be a bit more complicated than I expected to set up a CA and have a certificate verified by it. Currently, the built-in https support works in all browser but Chrome. Just access the site via `https://totara73` for example. You get a warning as the certificate is self-signed but in all browser except Chrome you can accept and continue.

**Comment by elkbullwinkle** [comment]
You can add your root cert into the keychain on the mac and make it trusted, it will make all the certs signed by that one trusted on your computer.

**Comment by markmetcalfe** [comment]
So the solution to this then is just adding instructions on how to add the totara cert as a trusted CA on each platform
